version: "3.8"

services:
  app:
    build: .
    container_name: app
    env_file: .env
    ports:
      - 8080:80
    volumes:
      - ./:/var/www/html

  mysql:
    container_name: mysql
    image: mysql
    volumes:
      - mysql_data:/var/lib/mysql
      - ./db:/docker-entrypoint-initdb.d
    environment:
      MYSQL_HOST: ${DB_HOST}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ROOT_PASSWORD: 1234

volumes:
  mysql_data: