version: "3.8"

services:
  app:
    build: .
    env_file: .env
    ports:
      - 8080:80
    volumes:
      - ./:/var/www/html

  mysql:
    image: mysql
    volumes:
      - mysql_data:/var/lib/mysql
      - ./db:/docker-entrypoint-initdb.d
    environment:
      MYSQL_HOST: ${DB_HOST}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}

volumes:
  mysql_data:

networks:
  default:
    name: 'storeapp'
